enum FBRpc
{
	SERVER_SEND_MAIN_DATA = 7828282,
	CLIENT_REQUEST_WORKBENCH_DATA,
	CLIENT_REQUEST_CRAFT_RECIPE,
	CLIENT_REQUEST_AUTH_ADD,
	CLIENT_REQUEST_AUTH_REMOVE,
	CLIENT_REQUEST_AUTH_CLEAR,
	SERVER_SEND_CRAFT_RESULT,
	SERVER_SEND_QUEUE_STATE
}
